- name: Docker configure in Ubuntu Machine
  hosts: all
  become: true
  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
      become: yes

    - name: Deploy the Image and Run as Container
      command: docker run -itd -p 8084:8081 cbabu85/insure-me-app:4.0
      become: yes
